### ISSUE TITLE
Stupid Question about the Commands

### ISSUE THREAD

**Issue by H3liumCat** [lkappelikonet/BigBrother#1]
Could you write me an explanation of the commands? Do I have to write them all together, of course with the correct details, i.e. RCON password, IP, port, channel ID and so on, in any channel? Or each command individually and in the respective channel.
Forgive my "stupid" questions. But I don't have that much experience in executing code yet. I can create a bot and invite it ;-) and give it the rights. Your name suggests that you are German? Then you can answer me in German if you like.

**Comment by SolarRadiation** [comment]
Which commands are you referring to? Discord commands?

**Comment by lkappelikonet** [comment]
> Could you write me an explanation of the commands? Do I have to write them all together, of course with the correct details, i.e. RCON password, IP, port, channel ID and so on, in any channel? Or each command individually and in the respective channel. Forgive my "stupid" questions. But I don't have that much experience in executing code yet. I can create a bot and invite it ;-) and give it the rights. Your name suggests that you are German? Then you can answer me in German if you like.

Name is polish, and I don't speak polish lol.
For the server setup, you call the isc command with the required info like the tutorial says, i have to fix the file stuff first though, include the batch command to install required deps first. Will close this for now, feel free to make a new ticket after I get stuff fixed and you're still having trouble.
